import React from 'react';
import Essay from './essays.js';

export default class SayNo extends Essay {
    render() {
      return (
          <div>
          <Essay title='Saying No' author='illuzen' />
          "No" is a really powerful word. I could say a lot about the cult-like One Taste organization, their sophisticated emotional intimidation tactics, their curiously named Orgasmic Meditation (OM) technique and their wonderful, oxytocin-rich community of practitioners, but that is for another time. I want to talk about a great exercise I encountered at one of their events. It was called "Practicing No". Here's how it goes:
          <ul>
          <li> Everybody in the group pairs up. Partners take turns being askers and tellers.</li>
          <li> Askers ask invitation questions of their teller partners. Tellers tell them no.</li>
          </ul>
          <br/>
          <br/> That's it. It's very simple and yet it had a profound effect on me. Altho my partner was definitely not someone I was trying to spend time with, I had a strong visceral reaction playing both the asker and the teller. When I heard "no" to my play-acted invitation to go to the movies, I felt like I had been punched. "What's wrong with this guy?" I thought, even as my bewilderment about my reaction took hold. After 2 minutes of rejections to my invitations, which varied from simple and unimportant to grandiose, I started to feel relaxed and playful. "No" didn't mean the end of the world. It didn't even mean it wouldn't happen in the future. It definitely didn't mean I was worth any less as a person, or that I wasn't worthy of love or that I deserved to be punished for asking. It just meant not right then. "Ask every time like it's the first time", as they said.
          <br/>
          <br/> On the telling side, there was a different kind of initial friction. I found my politeness patterns impeding my rejection. I didn't want to be mean. I already said "no" several times, he's bound to get his feelings hurt if I say it again. I experimented with different ways to soften it. "No, sorry". "Not today". "No, but thank you for offering". "I'm sorry, I can't". The soft nos actually felt worse than the hard nos after a few rounds, tho. I realized I wasn't really giving a clear signal, I was leading the other person on. It would have been different if I really just couldn't do it that day, but I was just saying that so they didn't feel so bad, to soften the blow.
          <br/>
          <br/> And why didn't I want him to feel bad? Was it empathy? Was I projecting my own rejection-scars onto him? Was I trying to protect myself from his anger? Was I protecting my reputation as a generous, thoughtful person? The motive was diffuse and unclear. "Soften the no" was deeply ingrained pattern I felt I had acquired at a young age, possibly from my mother. In any case, just practicing no a little bit was helpful for me in subtle and profound ways. (Before you sing the praises of One Taste for teaching people this wonderful skill, you should know that I personally watched their paid sales people harass a girl who clearly didn't know how to say no into spending money she said she didn't want to spend on their overpriced workshop, despite the fact she obviously felt really uncomfortable and trapped by them. In the end she seemed to like it, so things are a bit grey, as always.)
          <br/>
          <br/> It is astonishing in retrospect how simultaneously important and neglected this important skill is. Nobody in school ever had me practice saying no. My sex education course mentioned it in passing, but imagine if they had students practice asking for sexual contact and getting rejected. How much sexual frustration, anger over rejection, how much pain and violence could be avoided with this simple exercise? How many hours wasted in unwanted social situations could be reclaimed? How many dangerous situations with predators could be avoided by someone saying "no" as soon as their gut told them something was wrong? At the very least, women with religious sexual partners might be spared the <a href='https://biblicalgenderroles.com/2015/05/23/8-steps-to-confront-your-wifes-sexual-refusal/'>punishment they sometimes receive for refusing sex.</a>
          <br/>
          <br/> This lead me to wonder if maybe there is a reason not to teach people this skill. Empowering students to say no might make rebellion more common. "If I can say no to my classmate, I can say no to my teacher". This touches a lot of issues around authority and power and the assumptions embedded in our educational system. There are people to which we are obligated to say yes to, according to our cultural narrative. You come into the world thru your mother's body, her food becomes your body. This connected identity, trust and filial attachment is sometimes expressed as a feeling that parents are supreme authorities on some matters, that they are not to be questioned, doubted or disagreed with. "Honor thy father and mother", as that famous book on black magic says. The "terrible twos" are the age when the child starts to be able to say "no". They are called terrible because the task of parenting has become a relationship with another autonomous entity, one which does not always share or understand the parents' desires. This obviously complicates matters. This rebellion is sometimes met with force, spanking, loud angry voices or other riot control techniques. This punishment for saying "no" teaches people at a very early age that sometimes there are offers that you can't refuse. When an authority says something, you "have to" do it. Isn't it interesting how notions of obligation or compulsion are expressed by the verb "to have"? To have, to possess, to control, to consider property, to own. You "have to" do what those who "have you" want. Being a slave means your decision making authority has been exported to an external entity. As the child grows up, this vulnerability to notions of authority remains, and it is routinely exploited like a default password by entities well-meaning and malicious, from teachers to principals, police, mayors, priests, experts sitting in front of well-stocked bookcases, people with nice business cards and suits, anyone willing to write a book, people with chic glasses, armed with polysyllabic vocabularies and philosophy degrees, presidents, ancient masters, bearers of traditions, and of course anything calling itself "God".
          <br/>
          <br/>This feeling of not being able to say no creates both obedience and hidden friction in the form of intentional incompetence. "I'm sure she didn't mean to make Master's coffee so hot, it was an accident". It also creates absurdities and atrocities like <a href="https://godhatesfags.com/">"I don't hate fags, God does"</a> and <a href="https://en.wikipedia.org/wiki/Superior_orders">"I was just doing my job"</a> or it's little cousin "It's company policy". In fact, it is possibly to substitute "I won't" or "I haven't" for every instance of "I can't" without making sentences incoherent.
          <br/>
          <br/> Being able to say no is related to notions of political correctness or speech control. When people feel that they can't speak their minds accurately, then words lose meaning. Information has to be novel or surprising to be information. People living in cultures in which saying no is strongly discouraged still opt out of things, they just don't say so. This might manifest as someone agreeing to come to a party and finding an excuse at the last minute not to, or just not showing up. It might manifest as everyone telling a pollster they will vote for one candidate and then actually voting for another, or in worse situations, voting for a candidate that they actually don't want. It also connects to free markets and <a href="http://fooledbyrandomness.com/ConvexityScience.pdf">optionality.</a> When I am free to choose who I do business with, I have power. When I have only one option, I am a slave to a monopoly. "No" is feedback, which is essential for a system to behave intelligently.
          <br/>
          <br/> So do yourself a favor and get in the mirror and practice saying "NO!". Or don't, just remember that you could if you wanted to. I'll leave you with a couple quotes.
          <br/>
          <p>
          "Is the acorn better than the oak which is its fulness and completion? Is the parent better than the child into whom he has cast his ripened being? Whence, then, this worship of the past? The centuries are conspirators against the sanity and authority of the soul." - <a href="http://www.emersoncentral.com/selfreliance.htm">Ralph Waldo Emerson</a>
          </p>
          <p>"The ultimate weapon has always existed. Every man, every woman, and every child owns it. It's the ability to say No and take the consequences. The fear of death is the beginning of slavery." - Robert Anton Wilson
          </p>
          </div>
        )
      }
    }
